/* Generated By:JavaCC: Do not edit this line. JSONParserTreeConstants.java Version 5.0 */
package org.mwnorman.json;

public interface JSONParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=9d522db2142fe3e365dc0205e328b44d (do not edit this line) */
