/* Generated By:JavaCC: Do not edit this line. JSONParserTreeConstants.java Version 5.0 */
package org.mwnorman.json;

@SuppressWarnings("all")
public interface JSONParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=49c8f3c046c6c0634a7beb30ffa9c5bc (do not edit this line) */
